-- Config store written by urban-edge-vision-analytics main @ ffdd55a
-- Generated by a one-off script from CameraIn payloads; used by the upgrade test.
BEGIN TRANSACTION;
CREATE TABLE audit (
    id TEXT PRIMARY KEY,
    action TEXT NOT NULL,
    target_kind TEXT NOT NULL,
    target_id TEXT NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
);
CREATE TABLE bindings (
    id TEXT PRIMARY KEY,
    camera_id TEXT NOT NULL,
    pack_id TEXT NOT NULL,
    parameters_json TEXT NOT NULL DEFAULT '{}',
    report_interval_seconds INTEGER NOT NULL DEFAULT 5,
    enabled INTEGER DEFAULT 1,
    version TEXT DEFAULT '1.0.0',
    updated_at TEXT NOT NULL,
    UNIQUE(camera_id, pack_id),
    FOREIGN KEY (camera_id) REFERENCES cameras(id)
);
INSERT INTO "bindings" VALUES('4c8b884a-e570-44f7-89bf-4e3b469df706','north-approach','moving_object','{}',5,1,'1.0.0','2026-10-08T16:03:24.657602+00:00');
CREATE TABLE cameras (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    profile TEXT,
    rtsp_url TEXT,
    sample_fps REAL DEFAULT 1.0,
    detection_adapter TEXT DEFAULT 'mock',
    synthetic INTEGER DEFAULT 0,
    timezone TEXT DEFAULT 'UTC',
    enabled INTEGER DEFAULT 1,
    retention_days INTEGER DEFAULT 30
, host TEXT DEFAULT '', port INTEGER, username TEXT DEFAULT '', password_enc TEXT DEFAULT '', stream_path TEXT DEFAULT '', stream_quality TEXT DEFAULT 'main', channel INTEGER DEFAULT 1, rtsp_transport TEXT DEFAULT 'tcp', show_on_live INTEGER DEFAULT 1, created_at TEXT, updated_at TEXT);
INSERT INTO "cameras" VALUES('north-approach','North approach','tapo',NULL,1.0,'',0,'UTC',1,30,'192.0.2.20',554,'viewer','enc:v1:gAAAAABqx77Mq4iA3UycAwenhkVXJ81pLtWyzDFRaJqJ-fJBdPn-pwVp7A8ztnjdHu8d3OTUQx9z7iZH3JyuALpWwerB8OAt4w==','','sub',1,'tcp',1,'2026-10-08T16:03:24.580425+00:00','2026-10-08T16:03:24.580425+00:00');
INSERT INTO "cameras" VALUES('east-leg','East leg','hikvision',NULL,1.0,'',0,'UTC',1,30,'192.0.2.21',8554,'admin','enc:v1:gAAAAABqx77Mhcd_GpKOjB2O2FBUMpHPlBzlNPWczTw8ATsBvR5lRULjfqxss2zH8F0tyin1J9OTxnkOZC8wY-6IuIQBDcGdgw==','','main',2,'udp',0,'2026-10-08T16:03:24.593851+00:00','2026-10-08T16:03:24.593851+00:00');
INSERT INTO "cameras" VALUES('protect-token','Protect token','unifi_protect',NULL,1.0,'',0,'UTC',1,30,'192.0.2.30',7447,'','','/AbCdEf123','main',1,'tcp',1,'2026-10-08T16:03:24.608223+00:00','2026-10-08T16:03:24.608223+00:00');
INSERT INTO "cameras" VALUES('open-stream','Open stream','generic_rtsp',NULL,1.0,'',0,'UTC',1,30,'cam.example.test',554,'','','/live/main','main',1,'tcp',1,'2026-10-08T16:03:24.620179+00:00','2026-10-08T16:03:24.620179+00:00');
INSERT INTO "cameras" VALUES('mjpeg-cam','MJPEG cam','http_mjpeg',NULL,1.0,'',0,'UTC',0,30,'192.0.2.40',8080,'','','','main',1,'tcp',1,'2026-10-08T16:03:24.629763+00:00','2026-10-08T16:03:24.629763+00:00');
INSERT INTO "cameras" VALUES('laptop-webcam','Laptop webcam','browser_webrtc',NULL,1.0,'',0,'UTC',1,30,'',NULL,'','','','main',1,'tcp',1,'2026-10-08T16:03:24.639550+00:00','2026-10-08T16:03:24.639550+00:00');
INSERT INTO "cameras" VALUES('demo-feed','Demo feed','synthetic',NULL,1.0,'',1,'UTC',1,30,'',NULL,'','','','main',1,'tcp',1,'2026-10-08T16:03:24.648622+00:00','2026-10-08T16:03:24.648622+00:00');
CREATE TABLE events (
    event_id TEXT PRIMARY KEY,
    camera_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    pack_id TEXT,
    operator_review_recommended INTEGER NOT NULL DEFAULT 0,
    review_status TEXT NOT NULL DEFAULT 'none',
    review_note TEXT NOT NULL DEFAULT '',
    reviewed_at TEXT,
    payload_json TEXT NOT NULL
);
CREATE TABLE incidents (
    incident_id TEXT PRIMARY KEY,
    camera_id TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    payload_json TEXT NOT NULL
);
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
INSERT INTO "settings" VALUES('inference','{"interval_ms": 1500, "width": 640, "height": 360, "prompt_preset": "traffic_detection", "jpeg_quality": 80, "display_max_width": 1280}','2026-10-08T16:03:24.683754+00:00');
INSERT INTO "settings" VALUES('model','{"backend": "ollama", "endpoint": "", "model": "gemma4", "think": false, "max_tokens": 512, "timeout_s": 60.0, "label": "", "api_key_enc": "enc:v1:gAAAAABqx77MGzuMD8fyTtcXupHol5Y60DJ6RoCNGyeXNVFdI5FYZ1tvdROntPj2NEkhv3IRlqZk8LGJ1NEh_Nasn5p4PJKVsQ=="}','2026-10-08T16:03:24.692643+00:00');
CREATE TABLE speed_calibrations (
    id TEXT PRIMARY KEY,
    camera_id TEXT NOT NULL UNIQUE,
    gate_a_json TEXT NOT NULL,
    gate_b_json TEXT NOT NULL,
    real_world_distance_m REAL NOT NULL,
    homography_json TEXT,
    captured_at TEXT NOT NULL, posted_speed_kph REAL DEFAULT 50,
    FOREIGN KEY (camera_id) REFERENCES cameras(id)
);
INSERT INTO "speed_calibrations" VALUES('f7c89e16-e717-4109-b8e3-38d41c4978a5','east-leg','[[0.1, 0.5], [0.9, 0.5]]','[[0.1, 0.7], [0.9, 0.7]]',12.5,NULL,'2026-10-08T16:03:24.674273+00:00',40.0);
CREATE TABLE stop_zones (
    id TEXT PRIMARY KEY,
    camera_id TEXT NOT NULL UNIQUE,
    polygon_json TEXT NOT NULL,
    approach_direction TEXT NOT NULL DEFAULT 'N',
    compliance_threshold_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (camera_id) REFERENCES cameras(id)
);
INSERT INTO "stop_zones" VALUES('88844e58-e85e-45c3-9c64-7f3ce756cb4c','east-leg','[[0.1, 0.1], [0.9, 0.1], [0.9, 0.9]]','S','{"dwell_threshold_ms": 900}');
CREATE TABLE vehicle_counts (
    event_id TEXT PRIMARY KEY,
    camera_id TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    hour_bucket TEXT NOT NULL,        -- UTC hour, e.g. 2026-10-02T14
    vehicle_type TEXT NOT NULL,
    crossing TEXT NOT NULL,           -- a_to_b | b_to_a
    direction_label TEXT NOT NULL,
    track_id TEXT NOT NULL
);
CREATE TABLE zones (
    id TEXT PRIMARY KEY,
    camera_id TEXT NOT NULL,
    name TEXT NOT NULL,
    polygon_json TEXT NOT NULL,
    kind TEXT NOT NULL,
    FOREIGN KEY (camera_id) REFERENCES cameras(id)
);
CREATE INDEX idx_events_camera_ts ON events(camera_id, timestamp DESC);
CREATE INDEX idx_events_review ON events(operator_review_recommended, review_status);
CREATE INDEX idx_counts_camera_hour ON vehicle_counts(camera_id, hour_bucket);
COMMIT;
